name: Generate Snake Animation

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch: # Allow manual triggering

  push:
    branches:
      - main # Changed 'master' to 'main' for modern default branch naming

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake.svg animation
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark # GitHub dark palette for theme

      # Push snake.svg to the output branch
      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
